import { MenuCategory, MenuItem, TableLandmark, User, UserRole } from "./types";

export const VAT_RATE = 0.05;
export const SERVICE_FEE_RATE = 0.05; // 5% service fee

export const TRANSLATIONS = {
  EN: {
    welcome: "Welcome",
    table: "Table",
    menu: "Menu",
    orders: "Orders",
    kitchen: "Kitchen",
    admin: "Admin",
    owner: "Owner",
    developer: "Developer",
    login: "Login",
    logout: "Logout",
    guest: "Guest",
    staff: "Staff",
    search: "Search menu...",
    add: "Add",
    viewCart: "View Cart",
    placeOrder: "Place Order",
    total: "Total",
    subtotal: "Subtotal",
    vat: "VAT",
    service: "Service Fee",
    status: "Status",
    phoneOrder: "Phone Order",
    receipts: "Receipts",
    expenses: "Expenses",
    revenue: "Revenue",
    profit: "Net Profit",
    inStock: "In Stock",
    soldOut: "Sold Out",
    changeTable: "Change Table",
    myOrder: "Your Order",
    close: "Close",
    payOnline: "Pay Online",
    payCash: "Record Order",
    chefMenuControl: "Menu Availability",
    items: "Items",
    noOrders: "No active orders",
    noExpenses: "No expenses recorded",
    selectLandmark: "Select your landmark table",
    orderPlaced: "Order Placed!",
    preparing: "Preparing",
    ready: "Ready",
    pending: "Pending",
    completed: "Completed",
    cancelled: "Cancelled",
    manageMenu: "Manage Menu",
    back: "Back",
    edit: "Edit",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    editOrder: "Edit Order",
    addItem: "Add Item",
    remove: "Remove",
    price: "Price",
    quantity: "Qty",
    callWaiter: "Call Waiter",
    waiterCalled: "Waiter Called",
    serviceRequests: "Service Requests",
    noServiceRequests: "No active service requests",
    markResolved: "Mark Resolved",
    maintenanceMode: "Maintenance Mode",
    systemSettings: "System Settings",
    userManagement: "User Management",
    loginLogs: "Login Logs",
    appUnderMaintenance: "App Under Maintenance",
    maintenanceMessage: "We are currently upgrading our system to serve you better. Please try again later.",
    changeCredentials: "Change Credentials"
  },
  AM: {
    welcome: "እንኳን ደህና መጡ",
    table: "ጠረጴዛ",
    menu: "ምግብ ዝርዝር",
    orders: "ትዕዛዞች",
    kitchen: "ወጥ ቤት",
    admin: "አስተዳዳሪ",
    owner: "ባለቤት",
    developer: "ዴቨሎፐር",
    login: "ይግቡ",
    logout: "ውጣ",
    guest: "እንግዳ",
    staff: "ሰራተኛ",
    search: "ምግብ ይፈልጉ...",
    add: "ጨምር",
    viewCart: "ቅርጫት",
    placeOrder: "ዘዝ",
    total: "ጠቅላላ",
    subtotal: "ንዑስ ድምር",
    vat: "ታክስ",
    service: "የአገልግሎት ክፍያ",
    status: "ሁኔታ",
    phoneOrder: "የስልክ ትዕዛዝ",
    receipts: "ደረሰኞች",
    expenses: "ወጪዎች",
    revenue: "ገቢ",
    profit: "ትርፍ",
    inStock: "አለ",
    soldOut: "የለም",
    changeTable: "ጠረጴዛ ቀይር",
    myOrder: "ትዕዛዝዎ",
    close: "ዝጋ",
    payOnline: "በመስመር ላይ ይክፈሉ",
    payCash: "ትዕዛዝ ይመዝግቡ",
    chefMenuControl: "የምግብ ዝርዝር አስተዳደር",
    items: "እቃዎች",
    noOrders: "ምንም ትዕዛዝ የለም",
    noExpenses: "ምንም ወጪ የለም",
    selectLandmark: "የጠረጴዛዎን ስም ይምረጡ",
    orderPlaced: "ትዕዛዝ ተቀብለናል!",
    preparing: "እየተሰራ ነው",
    ready: "ዝግጁ",
    pending: "በመጠባበቅ ላይ",
    completed: "ተጠናቀቀ",
    cancelled: "ተሰርዟል",
    manageMenu: "ሜኑ ያስተዳድሩ",
    back: "ተመለስ",
    edit: "አስተካክል",
    saveChanges: "ለውጦችን አስቀምጥ",
    cancel: "ሰርዝ",
    editOrder: "ትዕዛዝ አስተካክል",
    addItem: "እቃ ጨምር",
    remove: "አስወግድ",
    price: "ዋጋ",
    quantity: "ብዛት",
    callWaiter: "አስተናጋጅ ጥራ",
    waiterCalled: "አስተናጋጅ ተጠርቷል",
    serviceRequests: "የአገልግሎት ጥያቄዎች",
    noServiceRequests: "ምንም የአገልግሎት ጥያቄ የለም",
    markResolved: "ተፈትቷል",
    maintenanceMode: "የጥገና ሁኔታ",
    systemSettings: "የሲስተም ቅንብሮች",
    userManagement: "የተጠቃሚ አስተዳደር",
    loginLogs: "የመግቢያ ምዝግብ ማስታወሻዎች",
    appUnderMaintenance: "መተግበሪያው በጥገና ላይ ነው።",
    maintenanceMessage: "የተሻለ አገልግሎት ለመስጠት ሲስተሙን እያሻሻልን ነው። እባክዎ ትንሽ ቆይተው ይሞክሩ።",
    changeCredentials: "መረጃዎችን ቀይር"
  }
};

export const LANDMARKS: TableLandmark[] = [
  { id: 'kilimanjaro', name: 'Kilimanjaro', description: "Africa's highest peak – as towering as our flavors!", imagePlaceholder: 'https://picsum.photos/400/300?random=1' },
  { id: 'victoria_falls', name: 'Victoria Falls', description: "The smoke that thunders.", imagePlaceholder: 'https://picsum.photos/400/300?random=2' },
  { id: 'serengeti', name: 'Serengeti', description: "Endless plains of taste.", imagePlaceholder: 'https://picsum.photos/400/300?random=3' },
  { id: 'okavango', name: 'Okavango', description: "A delta of deliciousness.", imagePlaceholder: 'https://picsum.photos/400/300?random=4' },
  { id: 'table_mountain', name: 'Table Mountain', description: "Flat-topped perfection.", imagePlaceholder: 'https://picsum.photos/400/300?random=5' },
  { id: 'sahara', name: 'Sahara', description: "Vast and heating up.", imagePlaceholder: 'https://picsum.photos/400/300?random=6' },
  { id: 'nile', name: 'Nile', description: "The source of life.", imagePlaceholder: 'https://picsum.photos/400/300?random=7' },
  { id: 'ngorongoro', name: 'Ngorongoro', description: "A crater of culinary delights.", imagePlaceholder: 'https://picsum.photos/400/300?random=8' },
  { id: 'namib', name: 'Namib', description: "Ancient sands, timeless recipes.", imagePlaceholder: 'https://picsum.photos/400/300?random=9' },
  { id: 'atlas', name: 'Atlas', description: "Peaks of Morocco.", imagePlaceholder: 'https://picsum.photos/400/300?random=10' },
  { id: 'zambezi', name: 'Zambezi', description: "Flowing with flavor.", imagePlaceholder: 'https://picsum.photos/400/300?random=11' },
  { id: 'congo_basin', name: 'Congo Basin', description: "Deep, rich, and green.", imagePlaceholder: 'https://picsum.photos/400/300?random=12' },
  { id: 'drakensberg', name: 'Drakensberg', description: "The Dragon Mountains.", imagePlaceholder: 'https://picsum.photos/400/300?random=13' },
  { id: 'blyde_canyon', name: 'Blyde Canyon', description: "Green canyons of gold.", imagePlaceholder: 'https://picsum.photos/400/300?random=14' },
  { id: 'baobabs', name: 'Avenue of Baobabs', description: "Trees of life.", imagePlaceholder: 'https://picsum.photos/400/300?random=15' },
];

export const INITIAL_MENU: MenuItem[] = [
  // Starters
  { id: '1', name: 'Harira Soup', description: 'Traditional Moroccan lentil and tomato soup.', price: 35, category: MenuCategory.STARTERS, isAvailable: true, imageUrl: 'https://picsum.photos/200/200?random=20', tags: ['vegan', 'halal'] },
  { id: '2', name: 'Sambusa Trio', description: 'Crispy pastry filled with spiced beef, lentils, and cheese.', price: 30, category: MenuCategory.STARTERS, isAvailable: true, imageUrl: 'https://picsum.photos/200/200?random=21', tags: ['halal', 'spicy'] },
  
  // Mains
  { id: '3', name: 'Chicken Jollof Rice', description: 'Smoky West African rice with grilled peri-peri chicken.', price: 65, category: MenuCategory.MAINS, isAvailable: true, imageUrl: 'https://picsum.photos/200/200?random=22', tags: ['halal', 'spicy'] },
  { id: '4', name: 'Bunny Chow', description: 'South African hollowed bread filled with lamb curry.', price: 70, category: MenuCategory.MAINS, isAvailable: true, imageUrl: 'https://picsum.photos/200/200?random=23', tags: ['halal', 'spicy'] },
  { id: '5', name: 'Tagine of Lamb', description: 'Slow-cooked with prunes, almonds, and apricots.', price: 85, category: MenuCategory.MAINS, isAvailable: true, imageUrl: 'https://picsum.photos/200/200?random=24', tags: ['halal', 'gf'] },

  // Sides
  { id: '6', name: 'Fried Plantains', description: 'Sweet, golden fried plantains.', price: 25, category: MenuCategory.SIDES, isAvailable: true, imageUrl: 'https://picsum.photos/200/200?random=25', tags: ['vegan', 'gf'] },
  { id: '7', name: 'Injera', description: 'Fermented teff flatbread.', price: 15, category: MenuCategory.SIDES, isAvailable: true, imageUrl: 'https://picsum.photos/200/200?random=26', tags: ['vegan'] },

  // Desserts
  { id: '8', name: 'Malva Pudding', description: 'Sweet apricot sponge cake with hot cream sauce.', price: 40, category: MenuCategory.DESSERTS, isAvailable: true, imageUrl: 'https://picsum.photos/200/200?random=27', tags: ['halal'] },
  
  // Drinks
  { id: '9', name: 'Zobo Drink', description: 'Hibiscus iced tea with ginger and pineapple.', price: 20, category: MenuCategory.BEVERAGES, isAvailable: true, imageUrl: 'https://picsum.photos/200/200?random=28', tags: ['vegan', 'gf'] },
  { id: '10', name: 'Rooibos Tea', description: 'Organic South African red bush tea.', price: 18, category: MenuCategory.BEVERAGES, isAvailable: true, imageUrl: 'https://picsum.photos/200/200?random=29', tags: ['vegan', 'gf'] },
];

export const DEMO_USERS: User[] = [
  { id: 'u1', username: 'chef', password: '123', role: UserRole.CHEF, name: 'Chef Musa' },
  { id: 'u2', username: 'admin', password: '123', role: UserRole.ADMIN, name: 'Manager Sarah' },
  { id: 'u3', username: 'owner', password: '123', role: UserRole.OWNER, name: 'Mr. Kofi' },
  { id: 'u4', username: 'dev', password: '123', role: UserRole.DEVELOPER, name: 'Dev Team' },
];