
import { MenuCategory, MenuItem, User, UserRole } from "./types";

export const VAT_RATE = 0.05;
export const SERVICE_FEE_RATE = 0.05; // 5% service fee

export const TRANSLATIONS = {
  EN: {
    welcome: "Welcome",
    table: "Table",
    menu: "Menu",
    orders: "Orders",
    kitchen: "Kitchen",
    admin: "Admin",
    owner: "Owner",
    developer: "Developer",
    login: "Login",
    logout: "Logout",
    guest: "Guest",
    staff: "Staff",
    search: "Search menu...",
    add: "Add",
    viewCart: "View Cart",
    placeOrder: "Place Order",
    total: "Total",
    subtotal: "Subtotal",
    vat: "VAT",
    service: "Service Fee",
    status: "Status",
    phoneOrder: "Phone Order",
    receipts: "Receipts",
    expenses: "Expenses",
    revenue: "Revenue",
    profit: "Net Profit",
    inStock: "In Stock",
    soldOut: "Sold Out",
    changeTable: "Change Table",
    myOrder: "Your Order",
    close: "Close",
    payOnline: "Pay Online",
    payCash: "Record Order",
    chefMenuControl: "Menu Availability",
    items: "Items",
    noOrders: "No active orders",
    noExpenses: "No expenses recorded",
    selectLandmark: "Select Your Table",
    orderPlaced: "Order Placed!",
    preparing: "Preparing",
    ready: "Ready",
    pending: "Pending",
    completed: "Completed",
    cancelled: "Cancelled",
    manageMenu: "Manage Menu",
    back: "Back",
    edit: "Edit",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    editOrder: "Edit Order",
    addItem: "Add Item",
    remove: "Remove",
    price: "Price",
    quantity: "Qty",
    callWaiter: "Call Waiter",
    waiterCalled: "Waiter Called",
    serviceRequests: "Service Requests",
    noServiceRequests: "No active service requests",
    markResolved: "Mark Resolved",
    maintenanceMode: "Maintenance Mode",
    systemSettings: "System Settings",
    userManagement: "User Management",
    loginLogs: "Login Logs",
    appUnderMaintenance: "App Under Maintenance",
    maintenanceMessage: "We are currently upgrading our system to serve you better. Please try again later.",
    changeCredentials: "Change Credentials",
    select: "Select",
    paid: "Paid",
    unpaid: "Unpaid",
    markPaid: "Mark Paid",
    combinePrint: "Combine & Print",
    printCombined: "Print Combined Bill",
    selected: "Selected"
  },
  AM: {
    welcome: "እንኳን ደህና መጡ",
    table: "ጠረጴዛ",
    menu: "ምግብ ዝርዝር",
    orders: "ትዕዛዞች",
    kitchen: "ወጥ ቤት",
    admin: "አስተዳዳሪ",
    owner: "ባለቤት",
    developer: "ዴቨሎፐር",
    login: "ይግቡ",
    logout: "ውጣ",
    guest: "እንግዳ",
    staff: "ሰራተኛ",
    search: "ምግብ ይፈልጉ...",
    add: "ጨምር",
    viewCart: "ቅርጫት",
    placeOrder: "ዘዝ",
    total: "ጠቅላላ",
    subtotal: "ንዑስ ድምር",
    vat: "ታክስ",
    service: "የአገልግሎት ክፍያ",
    status: "ሁኔታ",
    phoneOrder: "የስልክ ትዕዛዝ",
    receipts: "ደረሰኞች",
    expenses: "ወጪዎች",
    revenue: "ገቢ",
    profit: "ትርፍ",
    inStock: "አለ",
    soldOut: "የለም",
    changeTable: "ጠረጴዛ ቀይር",
    myOrder: "ትዕዛዝዎ",
    close: "ዝጋ",
    payOnline: "በመስመር ላይ ይክፈሉ",
    payCash: "ትዕዛዝ ይመዝግቡ",
    chefMenuControl: "የምግብ ዝርዝር አስተዳደር",
    items: "እቃዎች",
    noOrders: "ምንም ትዕዛዝ የለም",
    noExpenses: "ምንም ወጪ የለም",
    selectLandmark: "ጠረጴዛዎን ይምረጡ",
    orderPlaced: "ትዕዛዝ ተቀብለናል!",
    preparing: "እየተሰራ ነው",
    ready: "ዝግጁ",
    pending: "በመጠባበቅ ላይ",
    completed: "ተጠናቀቀ",
    cancelled: "ተሰርዟል",
    manageMenu: "ሜኑ ያስተዳድሩ",
    back: "ተመለስ",
    edit: "አስተካክል",
    saveChanges: "ለውጦችን አስቀምጥ",
    cancel: "ሰርዝ",
    editOrder: "ትዕዛዝ አስተካክል",
    addItem: "እቃ ጨምር",
    remove: "አስወግድ",
    price: "ዋጋ",
    quantity: "ብዛት",
    callWaiter: "አስተናጋጅ ጥራ",
    waiterCalled: "አስተናጋጅ ተጠርቷል",
    serviceRequests: "የአገልግሎት ጥያቄዎች",
    noServiceRequests: "ምንም የአገልግሎት ጥያቄ የለም",
    markResolved: "ተፈትቷል",
    maintenanceMode: "የጥገና ሁኔታ",
    systemSettings: "የሲስተም ቅንብሮች",
    userManagement: "የተጠቃሚ አስተዳደር",
    loginLogs: "የመግቢያ ምዝግብ ማስታወሻዎች",
    appUnderMaintenance: "መተግበሪያው በጥገና ላይ ነው።",
    maintenanceMessage: "የተሻለ አገልግሎት ለመስጠት ሲስተሙን እያሻሻልን ነው። እባክዎ ትንሽ ቆይተው ይሞክሩ።",
    changeCredentials: "መረጃዎችን ቀይር",
    select: "ይምረጡ",
    paid: "ተከፍሏል",
    unpaid: "አልተከፈለም",
    markPaid: "ተከፍሏል በል",
    combinePrint: "አጣምር እና አትም",
    printCombined: "የተጣመረ ደረሰኝ አትም",
    selected: "ተመርጧል"
  },
  TI: {
    welcome: "እንቋዕ ብደሓን መጻእኩም",
    table: "ጣውላ",
    menu: "ሜኑ",
    orders: "ትእዛዛት",
    kitchen: "ክሽነ",
    admin: "ኣመሓዳሪ",
    owner: "ዋና",
    developer: "ማዕበሊ",
    login: "እተው",
    logout: "ውጻእ",
    guest: "ጋሻ",
    staff: "ሰራሕተኛ",
    search: "ድለ...",
    add: "ውስኽ",
    viewCart: "ካርታ ርኣይ",
    placeOrder: "ዘዝ",
    total: "ጠቕላላ",
    subtotal: "ንኡስ ድምር",
    vat: "ታክስ",
    service: "ክፍሊት ኣገልግሎት",
    status: "ኩነታት",
    phoneOrder: "ትእዛዝ ብቴሌፎን",
    receipts: "ደረሰኝ",
    expenses: "ወጻኢታት",
    revenue: "ኣታዊ",
    profit: "ረብሓ",
    inStock: "ኣሎ",
    soldOut: "የለን",
    changeTable: "ጣውላ ቀይር",
    myOrder: "ትእዛዝካ",
    close: "ዓጽው",
    payOnline: "ኦንላይን ክፈል",
    payCash: "ትእዛዝ መዝግብ",
    chefMenuControl: "ምቁጽጻር ሜኑ",
    items: "ኣቁሑት",
    noOrders: "ዝኾነ ትእዛዝ የለን",
    noExpenses: "ዝኾነ ወጻኢ የለን",
    selectLandmark: "ጣውላ ምረጽ",
    orderPlaced: "ትእዛዝ ተቀቢልናዮ ኣለና!",
    preparing: "ይስራሕ ኣሎ",
    ready: "ድሉው",
    pending: "ይጽበ ኣሎ",
    completed: "ተወዲኡ",
    cancelled: "ተሰሪዙ",
    manageMenu: "ሜኑ ኣመሓድር",
    back: "ተመለስ",
    edit: "ኣመሓይሽ",
    saveChanges: "ለውጢ ቴ zach",
    cancel: "ሰርዝ",
    editOrder: "ትእዛዝ ኣመሓይሽ",
    addItem: "ኣቅሓ ወስኽ",
    remove: "ኣልግስ",
    price: "ዋጋ",
    quantity: "ብዝሒ",
    callWaiter: "ኣሰላፊ ጸውዕ",
    waiterCalled: "ኣሰላፊ ተጸዊዑ",
    serviceRequests: "ጠለባት ኣገልግሎት",
    noServiceRequests: "ዝኾነ ጠለብ የለን",
    markResolved: "ተፈቲሑ",
    maintenanceMode: "ናይ ጽገና ኩነታት",
    systemSettings: "ቅንብራት ሲስተም",
    userManagement: "ምሕደራ ተጠቀምቲ",
    loginLogs: "ሎግ መእተዊ",
    appUnderMaintenance: "ኣፕሊኬሽን ኣብ ጽገና ይርከብ",
    maintenanceMessage: "ብዝበለጸ ንምግልጋል ሲስተም ነመሓይሽ ኣለና። በጃኹም ደሓር ይፈትኑ።",
    changeCredentials: "መእተዊ ሓበሬታ ቀይር",
    select: "ምረጽ",
    paid: "ተከፊሉ",
    unpaid: "ኣይተከፍለን",
    markPaid: "ተከፊሉ በል",
    combinePrint: "ጥርኒፍካ ሕተም",
    printCombined: "ጥርኑፍ ደረሰኝ ሕተም",
    selected: "ተመሪጹ"
  },
  ES: {
    welcome: "Bienvenido",
    table: "Mesa",
    menu: "Menú",
    orders: "Pedidos",
    kitchen: "Cocina",
    admin: "Admin",
    owner: "Dueño",
    developer: "Desarrollador",
    login: "Iniciar Sesión",
    logout: "Cerrar Sesión",
    guest: "Invitado",
    staff: "Personal",
    search: "Buscar menú...",
    add: "Agregar",
    viewCart: "Ver Carrito",
    placeOrder: "Realizar Pedido",
    total: "Total",
    subtotal: "Subtotal",
    vat: "IVA",
    service: "Tarifa de Servicio",
    status: "Estado",
    phoneOrder: "Pedido Telefónico",
    receipts: "Recibos",
    expenses: "Gastos",
    revenue: "Ingresos",
    profit: "Ganancia Neta",
    inStock: "En Stock",
    soldOut: "Agotado",
    changeTable: "Cambiar Mesa",
    myOrder: "Su Pedido",
    close: "Cerrar",
    payOnline: "Pagar Online",
    payCash: "Registrar Pedido",
    chefMenuControl: "Disponibilidad Menú",
    items: "Artículos",
    noOrders: "Sin pedidos activos",
    noExpenses: "Sin gastos registrados",
    selectLandmark: "Seleccione Su Mesa",
    orderPlaced: "¡Pedido Realizado!",
    preparing: "Preparando",
    ready: "Listo",
    pending: "Pendiente",
    completed: "Completado",
    cancelled: "Cancelado",
    manageMenu: "Gestionar Menú",
    back: "Atrás",
    edit: "Editar",
    saveChanges: "Guardar Cambios",
    cancel: "Cancelar",
    editOrder: "Editar Pedido",
    addItem: "Agregar Artículo",
    remove: "Eliminar",
    price: "Precio",
    quantity: "Cant.",
    callWaiter: "Llamar Camarero",
    waiterCalled: "Camarero Llamado",
    serviceRequests: "Solicitudes Servicio",
    noServiceRequests: "Sin solicitudes",
    markResolved: "Marcar Resuelto",
    maintenanceMode: "Modo Mantenimiento",
    systemSettings: "Ajustes del Sistema",
    userManagement: "Gestión Usuarios",
    loginLogs: "Registros Acceso",
    appUnderMaintenance: "App en Mantenimiento",
    maintenanceMessage: "Estamos actualizando el sistema para servirle mejor. Por favor intente más tarde.",
    changeCredentials: "Cambiar Credenciales",
    select: "Seleccionar",
    paid: "Pagado",
    unpaid: "No Pagado",
    markPaid: "Marcar Pagado",
    combinePrint: "Combinar e Imprimir",
    printCombined: "Imprimir Factura Combinada",
    selected: "Seleccionado"
  },
  FR: {
    welcome: "Bienvenue",
    table: "Table",
    menu: "Menu",
    orders: "Commandes",
    kitchen: "Cuisine",
    admin: "Admin",
    owner: "Propriétaire",
    developer: "Développeur",
    login: "Connexion",
    logout: "Déconnexion",
    guest: "Invité",
    staff: "Personnel",
    search: "Rechercher...",
    add: "Ajouter",
    viewCart: "Voir Panier",
    placeOrder: "Commander",
    total: "Total",
    subtotal: "Sous-total",
    vat: "TVA",
    service: "Frais de Service",
    status: "Statut",
    phoneOrder: "Commande Tél.",
    receipts: "Reçus",
    expenses: "Dépenses",
    revenue: "Revenus",
    profit: "Bénéfice Net",
    inStock: "En Stock",
    soldOut: "Épuisé",
    changeTable: "Changer Table",
    myOrder: "Votre Commande",
    close: "Fermer",
    payOnline: "Payer en ligne",
    payCash: "Enregistrer",
    chefMenuControl: "Dispo. Menu",
    items: "Articles",
    noOrders: "Pas de commandes",
    noExpenses: "Pas de dépenses",
    selectLandmark: "Choisissez votre table",
    orderPlaced: "Commande passée!",
    preparing: "Préparation",
    ready: "Prêt",
    pending: "En attente",
    completed: "Terminé",
    cancelled: "Annulé",
    manageMenu: "Gérer Menu",
    back: "Retour",
    edit: "Modifier",
    saveChanges: "Enregistrer",
    cancel: "Annuler",
    editOrder: "Modifier Commande",
    addItem: "Ajouter Article",
    remove: "Supprimer",
    price: "Prix",
    quantity: "Qté",
    callWaiter: "Appeler Serveur",
    waiterCalled: "Serveur Appelé",
    serviceRequests: "Demandes Service",
    noServiceRequests: "Pas de demandes",
    markResolved: "Marquer Résolu",
    maintenanceMode: "Mode Maintenance",
    systemSettings: "Paramètres Système",
    userManagement: "Gestion Utilisateurs",
    loginLogs: "Journaux Connexion",
    appUnderMaintenance: "App en Maintenance",
    maintenanceMessage: "Nous mettons à jour le système pour mieux vous servir. Veuillez réessayer plus tard.",
    changeCredentials: "Changer Identifiants",
    select: "Sélectionner",
    paid: "Payé",
    unpaid: "Impayé",
    markPaid: "Marquer Payé",
    combinePrint: "Combiner et Imprimer",
    printCombined: "Imprimer Facture Combinée",
    selected: "Sélectionné"
  }
};

export const INITIAL_MENU: MenuItem[] = [
  // Starters
  { id: '1', name: 'Harira Soup', description: 'Traditional Moroccan lentil and tomato soup.', price: 35, category: MenuCategory.STARTERS, isAvailable: true, imageUrl: 'https://picsum.photos/200/200?random=20', tags: ['vegan', 'halal'] },
  { id: '2', name: 'Sambusa Trio', description: 'Crispy pastry filled with spiced beef, lentils, and cheese.', price: 30, category: MenuCategory.STARTERS, isAvailable: true, imageUrl: 'https://picsum.photos/200/200?random=21', tags: ['halal', 'spicy'] },
  
  // Mains
  { id: '3', name: 'Chicken Jollof Rice', description: 'Smoky West African rice with grilled peri-peri chicken.', price: 65, category: MenuCategory.MAINS, isAvailable: true, imageUrl: 'https://picsum.photos/200/200?random=22', tags: ['halal', 'spicy'] },
  { id: '4', name: 'Bunny Chow', description: 'South African hollowed bread filled with lamb curry.', price: 70, category: MenuCategory.MAINS, isAvailable: true, imageUrl: 'https://picsum.photos/200/200?random=23', tags: ['halal', 'spicy'] },
  { id: '5', name: 'Tagine of Lamb', description: 'Slow-cooked with prunes, almonds, and apricots.', price: 85, category: MenuCategory.MAINS, isAvailable: true, imageUrl: 'https://picsum.photos/200/200?random=24', tags: ['halal', 'gf'] },

  // Sides
  { id: '6', name: 'Fried Plantains', description: 'Sweet, golden fried plantains.', price: 25, category: MenuCategory.SIDES, isAvailable: true, imageUrl: 'https://picsum.photos/200/200?random=25', tags: ['vegan', 'gf'] },
  { id: '7', name: 'Injera', description: 'Fermented teff flatbread.', price: 15, category: MenuCategory.SIDES, isAvailable: true, imageUrl: 'https://picsum.photos/200/200?random=26', tags: ['vegan'] },

  // Desserts
  { id: '8', name: 'Malva Pudding', description: 'Sweet apricot sponge cake with hot cream sauce.', price: 40, category: MenuCategory.DESSERTS, isAvailable: true, imageUrl: 'https://picsum.photos/200/200?random=27', tags: ['halal'] },
  
  // Drinks
  { id: '9', name: 'Zobo Drink', description: 'Hibiscus iced tea with ginger and pineapple.', price: 20, category: MenuCategory.BEVERAGES, isAvailable: true, imageUrl: 'https://picsum.photos/200/200?random=28', tags: ['vegan', 'gf'] },
  { id: '10', name: 'Rooibos Tea', description: 'Organic South African red bush tea.', price: 18, category: MenuCategory.BEVERAGES, isAvailable: true, imageUrl: 'https://picsum.photos/200/200?random=29', tags: ['vegan', 'gf'] },
];

export const DEMO_USERS: User[] = [
  { id: 'u1', username: 'chef', password: '123', role: UserRole.CHEF, name: 'Chef Musa' },
  { id: 'u2', username: 'admin', password: '123', role: UserRole.ADMIN, name: 'Manager Sarah' },
  { id: 'u3', username: 'owner', password: '123', role: UserRole.OWNER, name: 'Mr. Kofi' },
  { id: 'u4', username: 'tinsae', password: 'atinzzz', role: UserRole.DEVELOPER, name: 'Tinsae' },
];
